language: php

php:
# aliased to a recent 7.x version
  - 7.2
services:
  - mysql

before_install:
  - mysql -u root --password="" < store/simple_stock.sql

# omitting "script:" will default to phpunit
script: phpunit --configuration phpunit_mysql.xml 

# Here is the magic part
deploy:
  # Use Github pages deploy process
  provider: pages
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  edge: true # opt in to dpl v2
  on:
    # Which branch on commit/push will trigger deployment
    branch: devop